### ISSUE TITLE
Area of improvement

### ISSUE THREAD

**Issue by kagaramag** [andresporras3423/youtubeClone#4]
- Bootstrap provided built-in media queries, you can take advantage of it and avoid to use them in you your CSS where necessary.
`<aside class="col-md-4 col-xs-12 aside-styles center">`
Here `col-md-4 col-xs-12` means that you are using bootstrap media queries, there is no need to use it in `aside-styles` class. If you wish to control the behaviour of this div on large screens, you can use `col-lg-4`
- I suggest that you use heading instead of `strong`. It is the best practices to improve search engine optimization

**Comment by andresporras3423** [comment]
strong tags were replaced
